# Generated by Django 5.0.6 on 2025-06-14 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(db_column='appointment_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('medical', 'MEDICAL'), ('beauty', 'BEAUTY'), ('hotel', 'HOTEL'), ('vaccine', 'VACCINE')], max_length=20)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(db_column='pet_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=30)),
                ('breed', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('fur_color', models.CharField(max_length=30)),
                ('image_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pets',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_column='user_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.TextField()),
                ('role', models.CharField(choices=[('Admin', 'ADMIN'), ('Owner', 'OWNER'), ('Staff', 'STAFF'), ('Vet', 'VET')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=10)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='BeautyServiceHistory',
            fields=[
                ('id', models.UUIDField(db_column='beauty_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, to='core.appointment')),
            ],
            options={
                'db_table': 'beauty_service_history',
            },
        ),
        migrations.CreateModel(
            name='HotelServiceHistory',
            fields=[
                ('id', models.UUIDField(db_column='hotel_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=30)),
                ('room_number', models.CharField(max_length=20)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, to='core.appointment')),
            ],
            options={
                'db_table': 'hotel_service_history',
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.UUIDField(db_column='record_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, to='core.appointment')),
            ],
            options={
                'db_table': 'medical_history',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.pet'),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.user'),
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.UUIDField(db_column='plan_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_type', models.TextField()),
                ('portion', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, to='core.pet')),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'db_table': 'nutrition_plans',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='approver',
            field=models.ForeignKey(db_column='approver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_appointments', to='core.user'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='owner',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(db_column='staff_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_appointments', to='core.user'),
        ),
        migrations.CreateModel(
            name='VaccinationHistory',
            fields=[
                ('id', models.UUIDField(db_column='vaccination_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.TextField()),
                ('vaccination_date', models.DateField()),
                ('next_due', models.DateField()),
                ('total_doses', models.IntegerField()),
                ('batch_number', models.CharField(max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, to='core.appointment')),
            ],
            options={
                'db_table': 'vaccination_history',
            },
        ),
    ]
